name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the resource-service image
      run: docker build ../service --file Dockerfile --tag resource-service:$(date +%s)
    - name: Build the producer image
      run: docker build ../producer --file Dockerfile --tag producer:$(date +%s)
